### ISSUE TITLE
How to test the login?

### ISSUE THREAD

**Issue by gustavolira** [technical-rex/spring-security-jwt#1]
Hi, 
Sorry to open a issue for this doubt, but I didn't any other place to do this.
I read your article at http://technicalrex.com/2015/02/20/stateless-authentication-with-spring-security-and-jwt/ with attention and started do this at my project.
I have 1 aplication (client) and another application (backend API with spring...), my doubt is witch is the url that I need to send my username and password for authentication and the parameters, this part is not clear to me.

Thank you for your attention and sorry for any inconvenience

**Comment by egillespie** [comment]
Hi @gustavolira! It's probably confusing because this tutorial doesn't use a username and password for the initial login. I'm using a "Sign In with Google" button so that I don't have to worry about a database to store user information.

The button is on index.html. There's some backend code to get that part working too, but if you want to use a form-based login you'll have to add that part on your own, then incorporate my JWT approach afterwards.

Hopefully that clears things up. I'll keep this issue open so I can double-back and clarify that point in the tutorial.
